[package]
name = "my_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.0"
bevy-inspector-egui = "0.23.3"
bevy_mod_picking = "0.18.0"
bevy_asset_loader = "0.20.0"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable hight optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
