[package]
name = "my_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.1", features = ["bevy_dev_tools"]}
bevy-inspector-egui = "0.25.2"
bevy_asset_loader = "0.21.0"
glam = "0.27.0"
isometric = { version = "0.1.0", path = "../bevy_projects/iso" }

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable hight optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3
