[package]
name = "my_game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.1"
bevy-inspector-egui = "0.18.3"
bevy_ecs_tilemap = { path = "../bevy_ecs_tilemap", version = "0.10" }
bevy_asset_loader = "0.16.0"

[profile.dev.package."*"]
opt-level = 3
[profile.dev]
opt-level = 1
