[package]
name = "my_game"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# TODO delete features = ["dynamic"] before releasing
[dependencies]
bevy = { version = "0.7", features = ["dynamic"] }
