[package]
name = "my_plugin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
debug = ["bevy-inspector-egui"]

[dependencies]
bevy = "0.7"

serde = "1.0"

rand = "0.8"

bevy-inspector-egui = { version = "0.11", optional = true }
